# Generated by Django 2.2.1 on 2019-07-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images'),
        ),
        migrations.AlterField(
            model_name='simplepost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos'),
        ),
    ]
