# Generated by Django 2.2.1 on 2019-07-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_notification_notificationbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationbox',
            name='notifications',
            field=models.ManyToManyField(blank=True, null=True, related_name='box', to='compte.Notification'),
        ),
    ]
