# Generated by Django 2.2.1 on 2019-07-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_auto_20190705_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
