# Generated by Django 2.2.1 on 2019-07-05 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0005_auto_20190705_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationbox',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notebox', to=settings.AUTH_USER_MODEL),
        ),
    ]
